### ISSUE TITLE
When there is a compilation error...

### ISSUE THREAD

**Issue by ctolkien** [tugberkugurlu/gulp-dnx#2]
Would it be possible to stop attempting to compile (until a file save takes place, which would retrigger the watch/compile process)?

**Comment by tugberkugurlu** [comment]
I don't think it's possible as kre doesn't give you that option I assume, maybe [DTH](https://github.com/aspnet/XRE/tree/82d89e82dbe973578a0b032cadf6ae8e25083ec9/src/Microsoft.Framework.DesignTimeHost) has that capability but I am not sure.
